apiVersion: managedservices.thecodingsheikh.io/v1alpha1
kind: Webapp
metadata:
  name: "ias-tenant-my-app-webapp"
  annotations:
    lab.backstage.io/add-to-catalog: "true"
    lab.backstage.io/system-type: app
    lab.backstage.io/component-type: service
    lab.backstage.io/lifecycle: managed
    lab.backstage.io/dependsOn: component:default/ias-tenant
    lab.backstage.io/title: Ias Tenant My App Webapp
    lab.backstage.io/name: ias-tenant-my-app-webapp
    lab.backstage.io/system: webapp
    lab.backstage.io/owners: ''
    lab.backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=ias-tenant-my-app-webapp'
    lab.backstage.io/links: |-
      [
        {
          "url": "http://ias-tenant-my-app-webapp.ias-tenant-my-app-webapp.svc.cluster.local",
          "title": "Internal Service",
          "icon": "web"
        }
      ]
    backstage.io/last-applied-configuration: '{"tenant":"component:default/ias-tenant","serviceType":"webapp","image":"nginx:1.27","replicas":2,"port":8080,"host":"","name":"my-app","env":[],"envFromSecrets":[],"resources":{"cpu":"100m","memory":"128Mi","cpuLimit":"500m","memoryLimit":"512Mi"}}'
    backstage.io/scaffolder-template: template:default/webapp
    backstage.io/immutable-fields: 'tenant,name'
  label:
    app.kubernetes.io/instance: 'ias-tenant-my-app-webapp'
spec:
  values:
    tenant: ias
    name: my-app
    image: nginx:1.27
    replicas: 2
    port: 8080
    host: 
    env:
    envFromSecrets:
    resources:
      cpu: 100m
      memory: 128Mi
      cpuLimit: 500m
      memoryLimit: 512Mi
