apiVersion: managedservices.thecodingsheikh.io/v1alpha1
kind: Webapp
metadata:
  name: "faisal-tenant-faisalapp-webapp"
  annotations:
    lab.backstage.io/add-to-catalog: "true"
    lab.backstage.io/system-type: app
    lab.backstage.io/component-type: service
    lab.backstage.io/lifecycle: managed
    lab.backstage.io/dependsOn: component:default/faisal-tenant
    lab.backstage.io/title: Faisal Tenant Faisalapp Webapp
    lab.backstage.io/name: faisal-tenant-faisalapp-webapp
    lab.backstage.io/system: webapp
    lab.backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=faisal-tenant-faisalapp-webapp'
    lab.backstage.io/links: |-
      [
        {
          "url": "http://faisal-tenant-faisalapp-webapp.faisal-tenant-faisalapp-webapp.svc.cluster.local",
          "title": "Internal Service",
          "icon": "web"
        }
      ]
    backstage.io/last-applied-configuration: '{"tenant":"component:default/faisal-tenant","serviceType":"webapp","image":"nginx:1.27","replicas":2,"port":8080,"host":"","name":"faisalapp","env":[],"envFromSecrets":[],"resources":{"cpu":"100m","memory":"128Mi","cpuLimit":"500m","memoryLimit":"512Mi"}}'
    backstage.io/scaffolder-template: template:default/webapp
    backstage.io/immutable-fields: 'tenant,name'
    backstage.io/scaffolder-edit-roles: 'admin,edit'
  label:
    app.kubernetes.io/instance: 'faisal-tenant-faisalapp-webapp'
spec:
  values:
    tenant: faisal
    name: faisalapp
    image: nginx:1.27
    replicas: 2
    port: 8080
    host: 
    env:
    envFromSecrets:
    resources:
      cpu: 100m
      memory: 128Mi
      cpuLimit: 500m
      memoryLimit: 512Mi
